name: Deploy Vendor React app to cpanel

# Trigger the workflow on push to main or staging branches
on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: |
      !contains(github.event.head_commit.message, '[skip deploy]')

    # Set the environment
    environment: ${{ github.ref_name == 'main' && 'prod' || 'staging' }}

    # Define deployment steps
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build the React application (Use environment variables from GitHub Environments)
      # Use the environment variables defined in the GitHub environment for the build process
      # CI=false to prevent React from treating the build as a CI environment which can cause warnings/errors
      - name: Build React app
        env:
          REACT_APP_API_BASE_URL: ${{ vars.REACT_APP_API_BASE_URL }}
          REACT_APP_FAV_ICON: ${{ vars.REACT_APP_FAV_ICON }}
        run: |
          echo "Bulding react app with API URL: $REACT_APP_API_BASE_URL"
          CI=false npm run build

      # Create Deployment Marker File for Verification
      - name: Create Deployment marker file
        run: |
          echo "${GITHUB_SHA}" > build/.deploy-marker

      # Deploy to cPanel via SSH (Uses secrets that are defined in the repository settings)
      - name: Check and Prepare Deployment Directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USER }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
            if [ ! -d "$DEPLOY_PATH" ]; then
                mkdir -p "$DEPLOY_PATH"
                echo "Created deployment directory: $DEPLOY_PATH"
            else
                echo "Deployment directory exists: $DEPLOY_PATH"
            fi

      # Upload built files to cPanel (build folder)
      - name: Upload files to cPanel
        uses: appleboy/scp-action@v0.1.7
        with:
          username: ${{ secrets.CPANEL_USER }}
          host: ${{ secrets.CPANEL_HOST }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          source: build/*
          target: "/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"

      # Verify Deployment using the marker file
      - name: Check Deployment
        uses: appleboy/ssh-action@v0.1.7
        with:
          username: ${{ secrets.CPANEL_USER }}
          host: ${{ secrets.CPANEL_HOST }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
            MARKER_FILE="$DEPLOY_PATH/build/.deploy-marker"
            if [ -f "$MARKER_FILE" ] && grep -q "${GITHUB_SHA}" "$MARKER_FILE"; then
                echo "Deployment successful. Files are present in $DEPLOY_PATH"
            else
                echo "Deployment Failed. No files found in $DEPLOY_PATH"
                exit 1
            fi

      # Set Correct Permissions on Deployed Files
      - name: Fix Permissions
        uses: appleboy/ssh-action@v0.1.7
        with:
          username: ${{ secrets.CPANEL_USER }}
          host: ${{ secrets.CPANEL_HOST }}
          key: ${{ secrets.CPANEL_SSH_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.CPANEL_USER }}/${{ secrets.DEPLOY_DIR }}"
            if [ -d "$DEPLOY_PATH" ] && [ ! -z "$DEPLOY_PATH" ] && [ "$DEPLOY_PATH" != "/home//" ]; then
                chmod -R 755 "$DEPLOY_PATH"
                echo "Permissions Fixed"
                echo "Deployment Completed"
            else
                echo "Error: Invalid deployment path- $DEPLOY_PATH"
                echo "Deployment Failed"
                exit 1
            fi
